apiVersion: v1
kind: ImageStream
metadata:
  name: kubevirt-installer
  namespace: ocp
spec:
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: quay.io/bardielle/kubevirt-ipi-instsller:latest
    importPolicy:
      scheduled: true
